SELECT 
    COMPANY_NAME, 
    COMPANY_ID, 
    FILING_DATE, 
    PERIOD, 
    FISCAL_YEAR, 
    FISCAL_PERIOD, 
    UNIT, 
    PREFERRED_LABEL, 
    TOTAL_REPORTED_AMOUNT, 
    TAG, 
    DATATYPE, 
    DOCUMENTATION, 
    COUNT(*) AS duplicate_count
FROM {{ ref('income_statement') }}
GROUP BY 
    COMPANY_NAME,
    COMPANY_ID,
    FILING_DATE,
    PERIOD,
    FISCAL_YEAR,
    FISCAL_PERIOD,
    UNIT,
    PREFERRED_LABEL,
    TOTAL_REPORTED_AMOUNT,
    TAG,
    DATATYPE, 
    DOCUMENTATION
HAVING COUNT(*) > 1